### ISSUE TITLE
Denoise Filter "Machine Learning" crashes Blender 2.91

### ISSUE THREAD

**Issue by kintuX** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#172]
While 'Machine Learning' denoiser works fine in viewport:
![RPR_denoiseML-viewportON-OK](https://user-images.githubusercontent.com/61623470/102836254-34ff5b00-43f9-11eb-83d5-7cbc4dfea509.jpg)

but final rendering (f12) crashes Blender right after denoising starts.  
[RPR_denoiseMLcrash.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5727190/RPR_denoiseMLcrash.zip)

Windows 10, Blender 2.91, RPR 3.0.13, NVidia GTX 1070 (driver v.460.89)

Console Error report & crashlog (attached below):
`read file
  Version 283 sub 8 date 2020-03-12 14:53 hash 63ee3db96107
read file
  Version 282 sub 7 date 2020-02-12 16:20 hash 77d23b0bd76f
Read blend: C:\Users\309\Desktop\RPR_denoiseML.blend
read file C:\Users\309\Desktop\RPR_denoiseML.blend
  Version 291 sub 10 date 2020-11-25 08:34 hash 0f45cab862b8
0  meshes freed
[MSG  @RIF]: Loaded RIF API version: 1.6.1.0xe4886697
I N F O :   M I O p e n   v e r s i o n :   2 . 0 . 1
 [MSG  @RIF]: Loading model: C:\Users\309\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\rprblender\data\models/denoise_c3_hdr_gamma_2.5.pb
I N F O :   M e m o r y :   a l l o c a t e d :   5 8 9 8 2 4 0 0 0 ,   b e s t :   4 7 1 8 5 9 2 0 0 ,   w o r s t :   2 8 2 1 9 3 9 2 0 0
 MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#306
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#306
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#307
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#307
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#307
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#307
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#307
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#307
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#308
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#308
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#243
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#252
MIOpen(OpenCL): Error [FindRecordUnsafe] Ill-formed record: key not found: C:\Users\309\AppData\Local/miopen/kernels/GeForce GTX 1070_15.OpenCL.2_0_1.ufdb.txt#309
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FFC6D8E46F0
Module  : nvopencl64.dll
Thread  : 00003050
Writing: C:\Users\309\AppData\Local\Temp\RPR_denoiseML.crash.txt`

[RPR_denoiseML.crash.txt.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5727165/RPR_denoiseML.crash.txt.zip)

**Comment by bsavery** [comment]
@kintuX we think this is fixed, please reopen if you see it again.

**Comment by kintuX** [comment]
Hey, hi!
Sorry for the late reply but,
Yes, I'm still having an issue...
[RPR_denoiseMLcrash.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6253493/RPR_denoiseMLcrash.crash.txt)
