### ISSUE TITLE
"Bump Node" not producing bumps

### ISSUE THREAD

**Issue by lenhone** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#440]
The "Bump Node" does not produce bumps when fed by a procedural texture with its vector input connected.

## Issue

No Bumps are generated. Bumps should be generated as supported nodes are used.

## Steps to Reproduce

Change below .blend file to rendered view, observe no bumps.
[rpr.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/7863917/rpr.blend.zip)

## System Setup (Environment)

OS: Linux, GPU: RX6800, Blender: 3.0.0, Plugin 3.3.15 / 3.3.16

## Detailed Description

As shown in the below image when the vector input is used on the checker texture the "Bump Node" no longer produces bumps. Possibly related to #209 (appears closed although not resolved). 

![rpr](https://user-images.githubusercontent.com/96949377/149361229-126be833-7a33-4157-9b77-f06351d529e2.png)

**Comment by VascoPi** [comment]
Thanks, added this to the ticket description.

**Comment by bsavery** [comment]
To check with 2.2.14

**Comment by lenhone** [comment]
> To check with 2.2.14

Tested with Radeon ProRender Blender Add-on Version 3.4.0 and 3.4.4, issue is not resolved. I am not sure if those use SDK 2.2.14. Does this have to be re-opened?

**Comment by bsavery** [comment]
Sorry, there is a pull request https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/520 using 2.2.14.  It should be fixed with that, if not we will reopen.

**Comment by ARozghon** [comment]
fixed with #520

**Comment by lenhone** [comment]
[Release 3.4.6](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/tree/v3.4.6) now appears to contain #520, however the original stated issue remains present (below image shows same nodes with different output in RPR 3.4.6 and Cycles), suggest reopening log.

![rpr-bump](https://user-images.githubusercontent.com/96949377/177025857-b53feff1-ec64-4718-9f64-0c9f6ecb9574.png)

**Comment by bsavery** [comment]
@ARozghon can you reproduce?

**Comment by ARozghon** [comment]
interesting setup with a Bump inside emission color input. will check it on Monday

**Comment by bsavery** [comment]
It's just to visualize the normal

**Comment by bsavery** [comment]
If the normal works "normally" then it's fine

**Comment by ARozghon** [comment]
![image](https://user-images.githubusercontent.com/68949117/180720967-3dd8904d-bb62-4b02-a506-d888215848e2.png)
interesting, in Blender 3.2 and RPR 3.4.6 all working fine

**Comment by ARozghon** [comment]
![image](https://user-images.githubusercontent.com/68949117/180721856-76ad9c98-d179-478e-8913-032d3ece8f54.png)
the same with the Principled BSDF shader
