### ISSUE TITLE
Crash on render

### ISSUE THREAD

**Issue by Skierman** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#569]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

Blender crashes when rendering with the GPU. This happens in any blend file (including the default scene). CPU rendering works as expected. 
## Issue

The crash takes place in final and interactive render modes, viewport render mode, when rendering the scene, as well as with upscaling/denoising disabled.
## Steps to Reproduce

This issue takes place in any blender scene as long as the GPU is selected.
## System Setup (Environment)

Windows 11 Home 22621.963

My device is a laptop with: AMD Ryzen 7 4800H with Radeon Graphics, NVIDIA RTX 3060 Laptop GPU (6GB VRAM), 16 GB RAM
NVIDIA Studio Driver version 527.56 (it still crashes with game ready drivers)

Blender 3.4.1

## Detailed Description

The console on Windows displays this when it crashes:

```0x00007FFDFFA4146C (0x0000000000000000 0x000000F5CE9FDBA9 0x000002521AED3100 0x0000000000000001), memcpy() + 0x17C bytes(s)
0x00007FFD984E0380 (0x000002521B281408 0x000002521B281400 0x000002521B2B0E88 0x000002521B2B0E80), DeleteRendererInstance() + 0x764E0 bytes(s)
0x00007FFD984EFB4C (0x0000000000000000 0x000002521B2718B0 0x0000000000000000 0x000002521B2B0240), DeleteRendererInstance() + 0x85CAC bytes(s)
0x00007FFD9854649F (0x0000000000000000 0x0000000000000000 0x000002521AEB4600 0x0000000000000100), DeleteRendererInstance() + 0xDC5FF bytes(s)
0x00007FFD984F6D64 (0x000002521AE62B00 0x000002521AE63B58 0x000000F5CE3FC4A0 0x000002521B266B00), DeleteRendererInstance() + 0x8CEC4 bytes(s)
0x00007FFD984F9794 (0x000002521AE62B00 0x0000000000000000 0x000002521AE62B00 0x00007FFE0AFA39F0), DeleteRendererInstance() + 0x8F8F4 bytes(s)
0x00007FFD984C80FA (0x000002521AE62B00 0x0000025100000002 0x000002521AF1D620 0x0000000000000008), DeleteRendererInstance() + 0x5E25A bytes(s)
0x00007FFD984C6DC2 (0x00000251579E4E80 0x0000000000000000 0x0000000000000000 0x0000000000000000), DeleteRendererInstance() + 0x5CF22 bytes(s)
0x00007FFE08C49363 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), _recalloc() + 0xA3 bytes(s)
0x00007FFE0AB126BD (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x1D bytes(s)
0x00007FFE0AFADFB8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x28 bytes(s)```

**Comment by longboarder241** [comment]
I had a similar issue using both the dev release and the last stable release with my RX580 8gb, the output was as follows;
The code before the first segfault was blender 3.5 git release and the second one was under blender 3.4.  I am running this under Artix linux
`Read prefs: /home/thomash/.config/blender/3.5/config/userpref.blend
2023-01-09 19:47:52,186 INFO rpr.engine.init [140224582082560]:  Core version: 2.2.16 build 0xb050a508
2023-01-09 19:47:52,195 INFO rpr.engine.init [140224582082560]:  RIF version: 1.7.1 build 0xfdc139ba
Error: Required device extension VK_KHR_deferred_host_operations is not supported.
2023-01-09 19:47:52,402 WARNING rpr.engine.init [140224582082560]:  ('Plugin is not registered', PosixPath('/home/thomash/.config/blender/3.5/scripts/addons/rprblender/HybridPro.so'), '')
2023-01-09 19:47:52,703 INFO rpr.utils.material_library [140224582082560]:  Material Library 2.0 found
2023-01-09 19:47:52,703 INFO rpr.material_library [140224582082560]:  Material library located at /home/thomash/Documents/Radeon ProRender/Material Library/Xml
Read blend: /home/thomash/Pictures/Personal Art/Low-poly model-extras.blend
Segmentation fault
thomas-sve15115fxs:[thomash]:~/.cache/yay/blender-git$ blender-3.4
2023-01-09 19:49:08,736 INFO rpr.engine.init [140307787244096]:  Core version: 2.2.16 build 0xb050a508
2023-01-09 19:49:08,741 INFO rpr.engine.init [140307787244096]:  RIF version: 1.7.1 build 0xfdc139ba
Error: Required device extension VK_KHR_deferred_host_operations is not supported.
2023-01-09 19:49:08,861 WARNING rpr.engine.init [140307787244096]:  ('Plugin is not registered', PosixPath('/home/thomash/.config/blender/3.4/scripts/addons/rprblender/HybridPro.so'), '')
2023-01-09 19:49:09,292 INFO rpr.utils.material_library [140307787244096]:  Material Library 2.0 found
2023-01-09 19:49:09,292 INFO rpr.material_library [140307787244096]:  Material library located at /home/thomash/Documents/Radeon ProRender/Material Library/Xml
Segmentation fault
`

**Comment by 1574242600** [comment]
+1
OS: archlinux 
kernel: 6.1.1-arch1-1
CPU:  e5 2666 v3
GPU: RX580 8g
driver: mesa 22.3.2-3     opencl-legacy-amdgpu-pro-icd 22.40
blender: 3.4.1
```
Read prefs: /home/nworm/.config/blender/3.4/config/userpref.blend
/run/user/1000/gvfs/ non-existent directory
2023-01-11 14:19:05,190 INFO rpr.engine.init [140313933574144]:  Core version: 2.2.16 build 0xb050a508
2023-01-11 14:19:05,198 INFO rpr.engine.init [140313933574144]:  RIF version: 1.7.1 build 0xfdc139ba
Error: Required device extension VK_KHR_deferred_host_operations is not supported.
2023-01-11 14:19:05,324 WARNING rpr.engine.init [140313933574144]:  ('Plugin is not registered', PosixPath('/home/nworm/.config/blender/3.4/scripts/addons/rprblender/HybridPro.so'), '')
2023-01-11 14:19:05,645 INFO rpr.utils.material_library [140313933574144]:  Material Library 2.0 found
2023-01-11 14:19:05,645 INFO rpr.material_library [140313933574144]:  Material library located at /home/nworm/Documents/Radeon ProRender/Material Library/Xml
2023-01-11 14:19:28,280 DEBUG rpr.init [140313933574144]:  view_update 140313678113032
2023-01-11 14:19:28,281 DEBUG rpr.viewport_engine [140313933574144]:  Start sync
2023-01-11 14:19:28,281 DEBUG rpr.properties.render [140313933574144]:  Syncing scene: Scene
[1]    102139 segmentation fault (core dumped)  blender
```

**Comment by Skierman** [comment]
I was having the same issue on Pop OS 22.10 (same computer as above) but downgrading my Nvidia drivers to version 515.65.01 fixed it for the most part. I still have to disable viewport denoising and upscaling but other than that it appears to work. I tried the same fix on Windows 11 but it resulted in my computer getting stuck in a BSOD loop.

**Comment by muhammadmnorouzi** [comment]
I have the same issue in blender 2.93

[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/10948044/blender.crash.txt)

**Comment by kintuX** [comment]
+1 (instant crash on render start using GPU) 

E```
rror   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FFB3AA03EDD
Module  : Northstar64.dll
Thread  : 00003b60
Writing: C:\Users\XXXXX\AppData\Local\Temp\blender.crash.txt
```
[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/11136497/blender.crash.txt)

**Comment by bsavery** [comment]
> +1 (instant crash on render start using GPU)
> 
> ```
> Error   : EXCEPTION_ACCESS_VIOLATION
> Address : 0x00007FFB3AA03EDD
> Module  : Northstar64.dll
> Thread  : 00003b60
> Writing: C:\Users\XXXXX\AppData\Local\Temp\blender.crash.txt
> ```
> 
> [blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/11136497/blender.crash.txt)

We need more details about the plugin version and GPU etc.

**Comment by kintuX** [comment]
> > +1 (instant crash on render start using GPU)
> > ```
> > Error   : EXCEPTION_ACCESS_VIOLATION
> > Address : 0x00007FFB3AA03EDD
> > Module  : Northstar64.dll
> > Thread  : 00003b60
> > Writing: C:\Users\XXXXX\AppData\Local\Temp\blender.crash.txt
> > ```
> >    
> > 
> >     
> >   
> > [blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/11136497/blender.crash.txt)
> 
> We need more details about the plugin version and GPU etc.
Have tested with RPR Blender addon Weekly Dev. builds: 3.5.5, 3.5.7 & 3.5.9 on Blender 3.3.6 LTS & 3.5.1 RCs
Using nVidia's GPUs: GTX 1070 & Quadro M5000 (528.49 drivers) 
NOTE: before drivers upgrade in March 2023 (from 47X.XX), RPR worked well

**Comment by bsavery** [comment]
3,5,9 should fix it, See this issue. https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/573

**Comment by kintuX** [comment]
Well, 3.5.9 still crashes, as noted (As sooas it calls for GPU; CPU starts fine).
If it helps, here's also prime report from Win. Console while starting Blender :
```
023-04-05 16:53:14,062 INFO rpr.engine.init [4348]:  Core version: 2.2.17 build 0xc1dd1d1b
2023-04-05 16:53:14,089 INFO rpr.engine.init [4348]:  RIF version: 1.7.1 build 0xfdc139ba
Warning: No supported ray tracing API. Building acceleration structures will be unavailable
Error: Fatal error: Unable to create Vulkan device, VkResult=-8
2023-04-05 16:53:14,165 WARNING rpr.engine.init [4348]:  ('Plugin is not registered', WindowsPath('C:/Users/309/AppData/Roaming/Blender Foundation/Blender/3.5/scripts/addons/rprblender/HybridPro.dll'), '')
2023-04-05 16:53:16,079 INFO rpr.material_library [4348]:  Material library located at C:\ProgramData\RadeonProRender\MaterialLibrary\Xml
```

**Comment by alolalo** [comment]
Same here, but I'm running it on Blender 3.2.2 and 3.6, and in both cases ProRender does not work as advertized in combination with my rx580. The rendering in the viewport is slower than Eevee, and only using the CPU will make it render properly. 

I hope that they will fix backwards compatibility with rx580 cards, as I was opting to get a 2nd card to make for better rendering as they are fairly cheap to get these days. But not having them supported by AMD themselves, is quite a bummer.

I did manage to get the render working on interactive, with the setting to accurate, but "final render" simply makes the aplication crash. So unless I am going to render, it's actually usefull unless they fix the buggy behavior on "older" graphics cards. 
\

**Comment by bsavery** [comment]
> Same here, but I'm running it on Blender 3.2.2 and 3.6, and in both cases ProRender does not work as advertized in combination with my rx580. The rendering in the viewport is slower than Eevee, and only using the CPU will make it render properly.
> 
> I hope that they will fix backwards compatibility with rx580 cards, as I was opting to get a 2nd card to make for better rendering as they are fairly cheap to get these days. But not having them supported by AMD themselves, is quite a bummer.
> 
> I did manage to get the render working on interactive, with the setting to accurate, but "final render" simply makes the aplication crash. So unless I am going to render, it's actually usefull unless they fix the buggy behavior on "older" graphics cards. \

It's frustrating because we've written the solution for older cards a few times.  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/638#issuecomment-1623813770

**Comment by mhashaam26** [comment]
Hello , any update on this issue ? I have an Rx570 and still this issue persists. Blender 3.6 (also tried on 2.8 & 2.9 ) with pro Radeon 3.6.0. & Driver Version Amd pro 22.q4 .

**Comment by bsavery** [comment]
Please read my above comment.
